name: Build and Push Container Image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      # Install and Setup
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      # Login and Metadata
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Metadata for Docker
        id: docker_meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{raw}}
            type=sha,format=short
      # Build
      - name: Build and Push container images
        uses: docker/build-push-action@v4.0.0
        id: build_and_push
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
      # Sign with cosign
      - name: Sign image with a key
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${images}
        env:
          TAGS: ${{ steps.docker_meta.outputs.tags }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
          # Sign with cosign
      # Verify the signatures
      - name: Verify the signatures with the public key in the environment variable
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign verify --key env://COSIGN_PUBLIC_KEY ${images} | jq
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
      - name: Verify the signatures with the public key in the repository
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign verify --key cosign.pub ${images} | jq
        env:
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
